language: php
dist: trusty
sudo: required

matrix:
  include:
    - php: 5.6
      env: DB=none;NOTESTS=1
    - php: 5.6
      env: DB=mysqli
    - php: 5.6
      env: DB=mariadb
    - php: 5.6
      env: DB=postgres
    - php: 5.6
      env: DB=sqlite3
    - php: 7.0
      env: DB=mariadb
    - php: 7.1
      env: DB=mariadb
    - php: 7.2
      env: DB=mariadb
    - php: 7.3
      env: DB=mariadb
    - php: 7.4snapshot
      env: DB=mariadb
    - php: nightly
      env: DB=mariadb
  allow_failures:
    - php: 7.3
    - php: 7.4snapshot
    - php: nightly
  fast_finish: true

env:
  global:
    - EXTNAME="anavaro/postlove"        # Extension name
    - SNIFF="1"                         # Code sniffer switch
    - IMAGE_ICC="1"                     # ICC profile sniffer switch
    - EPV="1"                           # Extension pre-validator switch
    - PHPBB_BRANCH="3.2.x"              # phpBB branch
    - EXTDEPS="0"                       # Extension dependencies switch

branches:
  only:
    - master
    - /^\d+\.\d+\.(?:\d+|x)/

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - travis/prepare-phpbb.sh $EXTNAME $PHPBB_BRANCH
  - cd ../../phpBB3
  - travis/prepare-extension.sh $EXTNAME $PHPBB_BRANCH
  - $TRAVIS_BUILD_DIR/travis/setup-extension-dependencies.sh $EXTNAME $EXTDEPS
  - travis/setup-phpbb.sh $DB $TRAVIS_PHP_VERSION $NOTESTS
  - $TRAVIS_BUILD_DIR/travis/prepare-epv.sh $EPV $NOTESTS

before_script:
  - travis/setup-database.sh $DB $TRAVIS_PHP_VERSION $NOTESTS

script:
  - sh -c "if [ '$SNIFF' != '0' ]; then travis/ext-sniff.sh $DB $TRAVIS_PHP_VERSION $EXTNAME $NOTESTS; fi"
  - sh -c "if [ '$IMAGE_ICC' != '0' ]; then travis/check-image-icc-profiles.sh $DB $TRAVIS_PHP_VERSION $NOTESTS; fi"
  - sh -c "if [ '$EPV' != '0' ] && [ '$NOTESTS' = '1' ]; then phpBB/vendor/bin/EPV.php run --dir='phpBB/ext/$EXTNAME/'; fi"
  - sh -c "if [ '$NOTESTS' != '1' ]; then phpBB/vendor/bin/phpunit --configuration phpBB/ext/$EXTNAME/travis/phpunit-$DB-travis.xml --bootstrap ./tests/bootstrap.php; fi"
