services:
    anavaro.postlove.listener:
        class: anavaro\postlove\event\main_listener
        arguments:
            - @auth
            - @cache
            - @config
            - @dbal.conn
            - @request
            - @template
            - @user
            - @controller.helper
            - %core.root_path%
            - %core.php_ext%
            - %core.table_prefix%
        tags:
            - { name: event.listener }
    anavaro.postlove.ajaxify:
        class: anavaro\postlove\controller\ajaxify
        arguments:
            - @config
            - @dbal.conn
            - @user
            - @anavaro.postlove.notifyhelper
            - %core.table_prefix%
    anavaro.postlove.lovelist:
        class: anavaro\postlove\controller\lovelist
        arguments:
            - @user
            - @controller.helper
            - @dbal.conn
            - @auth
            - @user_loader
            - @template
            - @pagination
            - @request
            - %core.table_prefix%
            - %core.root_path%
    anavaro.postlove.notifyhelper:
        class: anavaro\postlove\controller\notifyhelper
        arguments:
            - @config
            - @dbal.conn
            - @request
            - @template
            - @user
            - @service_container
            - %core.root_path%
            - %core.php_ext%
            - %core.table_prefix%
    notification.type.postlove:
        class: anavaro\postlove\notification\postlove
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @user_loader
            - @dbal.conn
            - @cache.driver
            - @user
            - @auth
            - @config
            - @controller.helper
            - %core.root_path%
            - %core.php_ext%
            - %tables.notification_types%
            - %tables.notifications%
            - %tables.user_notifications%
        tags:
            - { name: notification.type }